// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/cache_event.proto
// Protobuf C++ Version: 7.34.1

#include "proto/cache_event.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace chrono {

inline constexpr CacheEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ttl_ms_{::int64_t{0}},
        seq_{::uint64_t{0u}},
        timestamp_{::int64_t{0}},
        type_{static_cast< ::chrono::EventType >(0)} {}

template <typename>
constexpr CacheEvent::CacheEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CacheEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CacheEventDefaultTypeInternal {
  constexpr CacheEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheEventDefaultTypeInternal() {}
  union {
    CacheEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheEventDefaultTypeInternal _CacheEvent_default_instance_;
}  // namespace chrono
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2fcache_5fevent_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fcache_5fevent_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fcache_5fevent_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.ttl_ms_),
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.seq_),
        PROTOBUF_FIELD_OFFSET(::chrono::CacheEvent, _impl_.timestamp_),
        5,
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::chrono::CacheEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::chrono::_CacheEvent_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fcache_5fevent_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027proto/cache_event.proto\022\006chrono\"y\n\nCac"
    "heEvent\022\037\n\004type\030\001 \001(\0162\021.chrono.EventType"
    "\022\013\n\003key\030\002 \001(\014\022\r\n\005value\030\003 \001(\014\022\016\n\006ttl_ms\030\004"
    " \001(\003\022\013\n\003seq\030\005 \001(\004\022\021\n\ttimestamp\030\006 \001(\003*,\n\t"
    "EventType\022\007\n\003SET\020\000\022\n\n\006DELETE\020\001\022\n\n\006EXPIRE"
    "\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fcache_5fevent_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fcache_5fevent_2eproto = {
    false,
    false,
    210,
    descriptor_table_protodef_proto_2fcache_5fevent_2eproto,
    "proto/cache_event.proto",
    &descriptor_table_proto_2fcache_5fevent_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_proto_2fcache_5fevent_2eproto::offsets,
    file_level_enum_descriptors_proto_2fcache_5fevent_2eproto,
    file_level_service_descriptors_proto_2fcache_5fevent_2eproto,
};
namespace chrono {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
EventType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2fcache_5fevent_2eproto);
  return file_level_enum_descriptors_proto_2fcache_5fevent_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EventType_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class CacheEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CacheEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_._has_bits_);
};

CacheEvent::CacheEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chrono.CacheEvent)
}
PROTOBUF_NDEBUG_INLINE CacheEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::chrono::CacheEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        value_(arena, from.value_) {}

CacheEvent::CacheEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CacheEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CacheEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, ttl_ms_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, ttl_ms_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, ttl_ms_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:chrono.CacheEvent)
}
PROTOBUF_NDEBUG_INLINE CacheEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        value_(arena) {}

inline void CacheEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, ttl_ms_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, ttl_ms_) +
               sizeof(Impl_::type_));
}
CacheEvent::~CacheEvent() {
  // @@protoc_insertion_point(destructor:chrono.CacheEvent)
  SharedDtor(*this);
}
inline void CacheEvent::SharedDtor(MessageLite& self) {
  CacheEvent& this_ = static_cast<CacheEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CacheEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CacheEvent(arena);
}
constexpr auto CacheEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CacheEvent),
                                            alignof(CacheEvent));
}
constexpr auto CacheEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CacheEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CacheEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CacheEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CacheEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CacheEvent>(), &CacheEvent::ByteSizeLong,
              &CacheEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_._cached_size_),
          false,
      },
      &CacheEvent::kDescriptorMethods,
      &descriptor_table_proto_2fcache_5fevent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CacheEvent_class_data_ =
        CacheEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CacheEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CacheEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CacheEvent_class_data_.tc_table);
  return CacheEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2>
CacheEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CacheEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chrono::CacheEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .chrono.EventType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CacheEvent, _impl_.type_), 5>(),
     {8, 5, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.type_)}},
    // bytes key = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.key_)}},
    // bytes value = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.value_)}},
    // int64 ttl_ms = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CacheEvent, _impl_.ttl_ms_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.ttl_ms_)}},
    // uint64 seq = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CacheEvent, _impl_.seq_), 3>(),
     {40, 3, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.seq_)}},
    // int64 timestamp = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CacheEvent, _impl_.timestamp_), 4>(),
     {48, 4, 0,
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.timestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .chrono.EventType type = 1;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.type_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bytes key = 2;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes value = 3;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 ttl_ms = 4;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.ttl_ms_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // uint64 seq = 5;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.seq_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // int64 timestamp = 6;
    {PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.timestamp_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CacheEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:chrono.CacheEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003cU)) {
    ::memset(&_impl_.ttl_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.ttl_ms_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CacheEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CacheEvent& this_ = static_cast<const CacheEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CacheEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CacheEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:chrono.CacheEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .chrono.EventType type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // bytes key = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_key().empty()) {
      const ::std::string& _s = this_._internal_key();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // bytes value = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // int64 ttl_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_ttl_ms() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_ttl_ms(), target);
    }
  }

  // uint64 seq = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_seq() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_seq(), target);
    }
  }

  // int64 timestamp = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chrono.CacheEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CacheEvent::ByteSizeLong(const MessageLite& base) {
  const CacheEvent& this_ = static_cast<const CacheEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CacheEvent::ByteSizeLong() const {
  const CacheEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:chrono.CacheEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // bytes key = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_key());
      }
    }
    // bytes value = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_value());
      }
    }
    // int64 ttl_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_ttl_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_ttl_ms());
      }
    }
    // uint64 seq = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_seq() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_seq());
      }
    }
    // int64 timestamp = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // .chrono.EventType type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CacheEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CacheEvent*>(&to_msg);
  auto& from = static_cast<const CacheEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:chrono.CacheEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_ttl_ms() != 0) {
        _this->_impl_.ttl_ms_ = from._impl_.ttl_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_seq() != 0) {
        _this->_impl_.seq_ = from._impl_.seq_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CacheEvent::CopyFrom(const CacheEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:chrono.CacheEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheEvent::InternalSwap(CacheEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.type_)
      + sizeof(CacheEvent::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(CacheEvent, _impl_.ttl_ms_)>(
          reinterpret_cast<char*>(&_impl_.ttl_ms_),
          reinterpret_cast<char*>(&other->_impl_.ttl_ms_));
}

::google::protobuf::Metadata CacheEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace chrono
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fcache_5fevent_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
